from __future__ import annotations

from .models import SectionDefinition, TagDefinition

SCHEMA_VERSION = "tag_studio_craig_v1"


DEFAULT_MEMO_TYPES = [
    "Origination",
    "Renewal",
    "Amendment",
    "Annual Review",
    "Troubled Credit Review",
    "Approval Package",
    "Other",
]

DEFAULT_FACILITY_TYPES = [
    "Revolver",
    "Term Loan",
    "ABL",
    "CRE",
    "Equipment",
    "Acquisition Finance",
    "LOC",
    "Multiple",
    "Other",
]


DEFAULT_SECTIONS = [
    SectionDefinition(
        section_id="executive_summary",
        display_name="Executive Summary",
        description="High-level request, borrower, facility, approval rationale, and major risks.",
        aliases=["Overview", "Transaction Summary", "Credit Request", "Approval Request", "Executive Overview"],
        expected_tag_ids=["memo_readiness", "decision_blocker", "rco_follow_up_questions"],
        display_order=10,
    ),
    SectionDefinition(
        section_id="borrower_business",
        display_name="Borrower and Business Profile",
        description="Borrower background, business model, ownership, management, customer base, and industry.",
        aliases=["Borrower", "Company Overview", "Business Description", "Management", "Industry"],
        expected_tag_ids=["industry_business_model", "management_quality", "concentration_risk"],
        display_order=20,
    ),
    SectionDefinition(
        section_id="facility_structure",
        display_name="Facility Structure",
        description="Facility type, amount, tenor, pricing, amortization, purpose, availability, and repayment terms.",
        aliases=["Loan Structure", "Facility", "Credit Facility", "Terms and Conditions", "Sources and Uses"],
        expected_tag_ids=["facility_fit", "tenor_amortization_fit", "loan_purpose"],
        display_order=30,
    ),
    SectionDefinition(
        section_id="repayment_analysis",
        display_name="Repayment Analysis",
        description="Primary and secondary repayment sources, cash flow, DSCR, leverage, sensitivity, and projections.",
        aliases=["Cash Flow", "Debt Service", "Primary Repayment", "DSCR Analysis", "Sources of Repayment"],
        expected_tag_ids=[
            "primary_repayment_source",
            "repayment_support_strength",
            "cash_flow_metric_quality",
            "sensitivity_quality",
            "projection_reasonableness",
        ],
        display_order=40,
    ),
    SectionDefinition(
        section_id="financial_performance",
        display_name="Financial Performance",
        description="Historical performance, trends, liquidity, leverage, working capital, and addbacks.",
        aliases=["Financial Analysis", "Historical Performance", "Operating Performance", "Liquidity", "Leverage"],
        expected_tag_ids=[
            "financial_info_freshness",
            "addback_quality",
            "leverage_risk",
            "liquidity_support",
            "performance_trend",
            "working_capital_risk",
        ],
        display_order=50,
    ),
    SectionDefinition(
        section_id="collateral",
        display_name="Collateral and Borrowing Base",
        description="Collateral type, valuation, advance rates, borrowing base controls, lien position, and monitoring.",
        aliases=["Collateral", "Security", "Borrowing Base", "Collateral Analysis", "ABL Analysis"],
        expected_tag_ids=["collateral_support_strength", "borrowing_base_quality"],
        display_order=60,
    ),
    SectionDefinition(
        section_id="covenants_reporting",
        display_name="Covenants and Reporting",
        description="Financial covenants, headroom, reporting, monitoring, and compliance expectations.",
        aliases=["Covenants", "Financial Covenants", "Reporting Requirements", "Monitoring", "Compliance"],
        expected_tag_ids=["covenant_package_strength", "covenant_headroom_quality", "reporting_monitoring_adequacy"],
        display_order=70,
    ),
    SectionDefinition(
        section_id="guarantor_sponsor",
        display_name="Guarantor or Sponsor Support",
        description="Guarantor, owner, sponsor, or parent support and enforceability.",
        aliases=["Guarantor", "Sponsor", "Support", "Owner Support", "Parent Support"],
        expected_tag_ids=["guarantor_sponsor_support"],
        display_order=80,
    ),
    SectionDefinition(
        section_id="policy_exceptions",
        display_name="Policy Exceptions and Mitigants",
        description="Exceptions to policy, risk acceptance rationale, mitigants, and approval conditions.",
        aliases=["Exceptions", "Policy Exception", "Risk Acceptance", "Deviations", "Policy Compliance"],
        expected_tag_ids=["policy_exception_type", "exception_mitigation_quality", "risk_rating_support_quality"],
        display_order=90,
    ),
    SectionDefinition(
        section_id="risk_assessment",
        display_name="Risk Assessment",
        description="Key risks, weaknesses, mitigants, strengths, and open credit officer questions.",
        aliases=["Risks", "Strengths and Weaknesses", "Risk Factors", "Mitigants", "Credit Considerations"],
        expected_tag_ids=[
            "unsupported_assertion",
            "internal_inconsistency",
            "deal_strength",
            "deal_weakness",
            "mitigant_quality",
            "rco_follow_up_questions",
        ],
        display_order=100,
    ),
    SectionDefinition(
        section_id="approval_recommendation",
        display_name="Approval Recommendation",
        description="Recommendation, requested approval, conditions, final support, and decision rationale.",
        aliases=["Recommendation", "Approval", "Decision", "Credit Approval", "Conclusion"],
        expected_tag_ids=["memo_readiness", "decision_blocker", "structure_enhancement"],
        display_order=110,
    ),
]


DEFAULT_TAGS = [
    TagDefinition(
        tag_id="memo_readiness",
        label="Memo readiness",
        category="Completeness",
        data_type="enum",
        allowed_values=["Ready", "Minor gaps", "Material gaps", "Not ready"],
        required=True,
        help_text="Whether the memo is ready for an RCO-style review.",
    ),
    TagDefinition(
        tag_id="decision_blocker",
        label="Decision blocker",
        category="Completeness",
        data_type="boolean",
        required=True,
        evidence_required=True,
        help_text="Whether missing or weak information blocks a credit view.",
    ),
    TagDefinition(
        tag_id="required_section_status",
        label="Required section status",
        category="Completeness",
        data_type="enum",
        allowed_values=["Present complete", "Present incomplete", "Missing", "N/A", "Unclear"],
        required=True,
        evidence_required=True,
        help_text="Completeness of the selected canonical section.",
    ),
    TagDefinition(
        tag_id="missing_section_severity",
        label="Missing section severity",
        category="Completeness",
        data_type="enum",
        allowed_values=["None", "Low", "Moderate", "High", "Critical"],
        required=True,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="rco_follow_up_questions",
        label="RCO follow-up questions",
        category="Completeness",
        data_type="long_text",
        required=False,
        help_text="Questions an RCO would need answered before rendering a view.",
    ),
    TagDefinition(
        tag_id="loan_purpose",
        label="Loan purpose",
        category="Review Context",
        data_type="text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="industry_business_model",
        label="Industry / business model",
        category="Review Context",
        data_type="long_text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="financial_info_freshness",
        label="Financial information freshness",
        category="Financial Analysis",
        data_type="enum",
        allowed_values=["Current", "Acceptable", "Stale", "Missing", "Unclear"],
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="primary_repayment_source",
        label="Primary repayment source",
        category="Repayment",
        data_type="long_text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="repayment_support_strength",
        label="Repayment support strength",
        category="Repayment",
        data_type="number",
        required=False,
        evidence_required=True,
        scoring_use="underwriting_strength_score",
        help_text="0-5 score where 5 is strongest support.",
    ),
    TagDefinition(
        tag_id="cash_flow_metric_quality",
        label="Cash flow metric quality",
        category="Repayment",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Missing", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="addback_quality",
        label="Addback quality",
        category="Financial Analysis",
        data_type="enum",
        allowed_values=["Well supported", "Partially supported", "Aggressive", "Missing", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="sensitivity_quality",
        label="Sensitivity quality",
        category="Repayment",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Missing", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="projection_reasonableness",
        label="Projection reasonableness",
        category="Repayment",
        data_type="enum",
        allowed_values=["Reasonable", "Somewhat aggressive", "Aggressive", "Unsupported", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="leverage_risk",
        label="Leverage risk",
        category="Financial Analysis",
        data_type="enum",
        allowed_values=["Low", "Moderate", "Elevated", "High", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="liquidity_support",
        label="Liquidity support",
        category="Financial Analysis",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Insufficient", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="performance_trend",
        label="Performance trend",
        category="Financial Analysis",
        data_type="enum",
        allowed_values=["Improving", "Stable", "Declining", "Volatile", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="concentration_risk",
        label="Concentration risk",
        category="Business Risk",
        data_type="enum",
        allowed_values=["Low", "Moderate", "Elevated", "High", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="working_capital_risk",
        label="Working capital risk",
        category="Financial Analysis",
        data_type="enum",
        allowed_values=["Low", "Moderate", "Elevated", "High", "N/A", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="management_quality",
        label="Management quality",
        category="Business Risk",
        data_type="enum",
        allowed_values=["Strong", "Acceptable", "Weak", "Unproven", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="facility_fit",
        label="Facility fit",
        category="Structure",
        data_type="enum",
        allowed_values=["Strong fit", "Acceptable fit", "Weak fit", "Misaligned", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="tenor_amortization_fit",
        label="Tenor / amortization fit",
        category="Structure",
        data_type="enum",
        allowed_values=["Strong", "Acceptable", "Weak", "Misaligned", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="covenant_package_strength",
        label="Covenant package strength",
        category="Structure",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Missing", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="covenant_headroom_quality",
        label="Covenant headroom quality",
        category="Structure",
        data_type="enum",
        allowed_values=["Well supported", "Adequate", "Thin", "Unsupported", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="reporting_monitoring_adequacy",
        label="Reporting / monitoring adequacy",
        category="Structure",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Missing", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="collateral_support_strength",
        label="Collateral support strength",
        category="Collateral",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Insufficient", "N/A", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="borrowing_base_quality",
        label="Borrowing base quality",
        category="Collateral",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Missing", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="guarantor_sponsor_support",
        label="Guarantor / sponsor support",
        category="Mitigants",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "None", "N/A", "Unclear"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="policy_exception_type",
        label="Policy exception type",
        category="Policy",
        data_type="multi_select",
        allowed_values=["None", "Leverage", "Collateral", "Covenant", "Financial information", "Tenor", "Pricing", "Other"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="exception_mitigation_quality",
        label="Exception mitigation quality",
        category="Policy",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Missing", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="risk_rating_support_quality",
        label="Risk rating support quality",
        category="Risk Rating",
        data_type="enum",
        allowed_values=["Well supported", "Adequate", "Weak", "Unsupported", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="unsupported_assertion",
        label="Unsupported assertion",
        category="Risk Assessment",
        data_type="long_text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="internal_inconsistency",
        label="Internal inconsistency",
        category="Risk Assessment",
        data_type="long_text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="deal_strength",
        label="Deal strength",
        category="Risk Assessment",
        data_type="long_text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="deal_weakness",
        label="Deal weakness",
        category="Risk Assessment",
        data_type="long_text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="mitigant_quality",
        label="Mitigant quality",
        category="Risk Assessment",
        data_type="enum",
        allowed_values=["Strong", "Adequate", "Weak", "Missing", "N/A"],
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="structure_enhancement",
        label="Structure enhancement opportunity",
        category="Structure Enhancement",
        data_type="long_text",
        required=False,
        evidence_required=True,
    ),
    TagDefinition(
        tag_id="completeness_score",
        label="Completeness score",
        category="Scoring",
        data_type="number",
        required=False,
        scoring_use="completeness_score",
        help_text="0-100 advisory score.",
    ),
    TagDefinition(
        tag_id="underwriting_strength_score",
        label="Underwriting strength score",
        category="Scoring",
        data_type="number",
        required=False,
        scoring_use="underwriting_strength_score",
        help_text="0-100 advisory score.",
    ),
    TagDefinition(
        tag_id="outcome_label",
        label="Outcome label",
        category="Outcome",
        data_type="enum",
        allowed_values=["Performing", "Covenant breach", "Past due", "Criticized", "Non-accrual", "Default", "Charge-off", "Refinanced out", "Unknown"],
        export_use="memo",
        help_text="Use only when outcome data is available and review boundary is clear.",
    ),
]
