from __future__ import annotations

import textwrap
from pathlib import Path

import fitz  # type: ignore

OUTPUT_PATH = Path("test_fixtures/synthetic_middle_market_credit_memo.pdf")


SECTIONS = [
    (
        "TRANSACTION SUMMARY",
        [
            "This synthetic credit memo supports the renewal and modest increase of a senior secured revolving credit facility for Cedar Valley Components, Inc., a privately held distributor of industrial replacement parts. The request is for a $22.5 million revolving line of credit, including a $2.0 million letter of credit sublimit, to refinance the existing facility and support seasonal working capital needs.",
            "The borrower generated fiscal year revenue of $186.4 million and adjusted EBITDA of $18.7 million. The proposed structure is intended to preserve liquidity during seasonal inventory builds while maintaining senior leverage below 2.50x and fixed charge coverage above 1.20x.",
            "Approval is recommended subject to updated field exam, borrowing base reporting, monthly financial statements, and confirmation that customer concentration remains below policy tolerance after the pending customer contract renewal.",
        ],
    ),
    (
        "COMPANY OVERVIEW",
        [
            "Cedar Valley Components, Inc. is a Midwest-based distributor serving food processing, packaging, and light manufacturing customers. The company has operated for 31 years and maintains six regional distribution centers. Revenue is diversified across approximately 1,850 active customers, although the top customer represented 18.4 percent of fiscal year revenue.",
            "Management is considered experienced and stable. The CEO has served in the role for 12 years, the CFO joined seven years ago, and the operating team has a demonstrated record of managing inventory turns through demand cycles. Ownership is concentrated in the founding family, which has historically retained cash in the business.",
        ],
    ),
    (
        "LOAN STRUCTURE",
        [
            "The proposed facility is a $22.5 million senior secured revolving credit facility with a three-year tenor. Availability is governed by a borrowing base equal to 85 percent of eligible accounts receivable plus 55 percent of eligible inventory, less reserves. The facility includes a springing fixed charge coverage covenant tested when availability falls below 15 percent of the borrowing base.",
            "The structure fits the seasonal working capital purpose, but the requested increase creates thinner availability during the third quarter inventory build. The memo recommends adding monthly borrowing base certificates and a collateral reporting package that includes inventory aging, customer concentration, and dilution reporting.",
        ],
    ),
    (
        "CASH FLOW AND DEBT SERVICE",
        [
            "Primary repayment is expected to come from operating cash flow generated by recurring replacement-part sales. Fiscal year adjusted EBITDA was $18.7 million compared with cash interest expense of $2.1 million and scheduled term debt amortization of $3.4 million. Fixed charge coverage was 1.42x, compared with the bank's minimum expectation of 1.20x.",
            "Base case projections show revenue growth of 4.0 percent and EBITDA margin compression of 40 basis points as freight and labor costs normalize slowly. Under the downside case, a 7.5 percent revenue decline and 100 basis point margin compression would reduce fixed charge coverage to 1.13x, below the proposed covenant threshold.",
            "The downside sensitivity is the central underwriting weakness. The memo partially mitigates this risk through borrowing base controls, springing covenant protection, and management's demonstrated ability to reduce discretionary inventory purchases.",
        ],
    ),
    (
        "HISTORICAL PERFORMANCE",
        [
            "Revenue increased from $154.2 million to $186.4 million over the last three fiscal years. Gross margin declined from 24.8 percent to 23.6 percent because of freight costs and pricing lag. Adjusted EBITDA increased from $15.9 million to $18.7 million, although the addback schedule includes $1.1 million of owner compensation normalization and $0.6 million of nonrecurring warehouse consolidation expense.",
            "Liquidity is adequate but not strong. Cash balances averaged $3.2 million, and revolver availability averaged $6.8 million during the last twelve months. Availability reached a low point of $2.9 million during the September inventory build, which supports the recommendation for tighter collateral monitoring.",
        ],
    ),
    (
        "SECURITY AND BORROWING BASE",
        [
            "Collateral consists primarily of accounts receivable and inventory. The most recent field exam reported eligible accounts receivable of $24.1 million, eligible inventory of $19.8 million, and net availability of $7.4 million after reserves. Dilution was 3.2 percent, and receivables over 90 days represented 4.1 percent of gross accounts receivable.",
            "The borrowing base is acceptable, subject to updated field exam and monthly reporting. Inventory is diversified across standard replacement components, but the memo notes that approximately $4.3 million of inventory relates to slower-moving specialty parts. The proposed inventory advance rate is acceptable only if slow-moving reserves are refreshed quarterly.",
        ],
    ),
    (
        "FINANCIAL COVENANTS",
        [
            "The proposed covenant package includes a springing fixed charge coverage covenant of 1.10x, tested when excess availability falls below 15 percent. The memo also recommends a maximum senior leverage covenant of 2.75x tested quarterly. Projected covenant headroom is adequate in the base case but tight in the downside case.",
            "Reporting requirements include monthly borrowing base certificates, monthly internally prepared financial statements, quarterly covenant certificates, annual CPA-reviewed financial statements, and annual field exam. The reporting package is appropriate for the facility size and collateral profile.",
        ],
    ),
    (
        "POLICY COMPLIANCE AND EXCEPTIONS",
        [
            "The memo identifies one policy exception related to customer concentration because the top customer exceeds the 15 percent guideline. The exception is mitigated by the customer's investment-grade profile, 14-year relationship history, low receivable dilution, and absence of material payment delays.",
            "Risk rating support is adequate but should be strengthened by explicitly connecting downside fixed charge coverage, availability lows, and customer concentration to the proposed pass rating. The memo should also state whether the pending top-customer contract renewal is fully executed before closing.",
        ],
    ),
    (
        "STRENGTHS, WEAKNESSES, AND RISK FACTORS",
        [
            "Strengths include experienced management, long operating history, recurring demand from replacement-part customers, adequate historical cash flow, and collateral monitoring through the borrowing base. Weaknesses include customer concentration, tight downside fixed charge coverage, seasonal availability pressure, and reliance on inventory values that require updated reserves.",
            "The most important follow-up questions are whether the top-customer contract renewal has been signed, whether the updated field exam confirms the borrowing base assumptions, and whether the downside case should trigger a stronger covenant package or lower inventory advance rate.",
        ],
    ),
    (
        "APPROVAL RECOMMENDATION",
        [
            "The synthetic recommendation is to approve the renewal and increase subject to updated field exam, executed top-customer contract renewal, quarterly inventory reserve refresh, monthly borrowing base reporting, and a springing fixed charge coverage covenant. The memo is substantially complete but should be strengthened by adding a clearer downside analysis bridge and explicit risk rating rationale.",
            "Suggested structure enhancements include lowering the inventory advance rate to 50 percent until the field exam is complete, adding a customer concentration reporting trigger at 20 percent, and requiring lender consent for dividends while availability is below 20 percent.",
        ],
    ),
]


def add_header_footer(page: fitz.Page, page_number: int) -> None:
    width = page.rect.width
    page.draw_rect(fitz.Rect(36, 28, width - 36, 58), color=(0.08, 0.19, 0.30), fill=(0.08, 0.19, 0.30))
    page.insert_text((48, 48), "SYNTHETIC CREDIT MEMO - TAG STUDIO TEST FIXTURE", fontsize=10, color=(1, 1, 1))
    page.insert_text((48, page.rect.height - 32), "Synthetic data only. No real borrower or customer information.", fontsize=8, color=(0.35, 0.35, 0.35))
    page.insert_text((width - 82, page.rect.height - 32), f"Page {page_number}", fontsize=8, color=(0.35, 0.35, 0.35))


def write_lines(doc: fitz.Document, lines: list[tuple[str, str]]) -> None:
    page_number = 1
    page = doc.new_page(width=612, height=792)
    add_header_footer(page, page_number)
    y = 82
    margin_left = 48
    max_y = 728

    for kind, text in lines:
        if kind == "heading":
            wrapped = [text]
            font_size = 12
            line_height = 18
            color = (0.05, 0.20, 0.32)
        else:
            wrapped = textwrap.wrap(text, width=92)
            font_size = 9.5
            line_height = 13
            color = (0.08, 0.08, 0.08)

        needed = len(wrapped) * line_height + (10 if kind == "heading" else 8)
        if y + needed > max_y:
            page_number += 1
            page = doc.new_page(width=612, height=792)
            add_header_footer(page, page_number)
            y = 82

        if kind == "heading":
            page.draw_rect(fitz.Rect(margin_left, y - 12, 564, y + 8), color=(0.88, 0.93, 0.96), fill=(0.88, 0.93, 0.96))
            y += 2

        for line in wrapped:
            page.insert_text((margin_left, y), line, fontsize=font_size, color=color)
            y += line_height
        y += 8


def build_pdf(output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = fitz.open()
    lines: list[tuple[str, str]] = [
        ("heading", "CRAIG SYNTHETIC MIDDLE MARKET CREDIT MEMO"),
        ("body", "This PDF is a fully synthetic testing fixture for Tag Studio. It is designed to look like a middle market credit memo while containing no real customer, borrower, or bank information."),
        ("body", "Memo Type: Renewal. Facility Type: Revolver. Borrower Segment: Middle Market. Review Boundary: as-of memo review only."),
    ]
    for heading, paragraphs in SECTIONS:
        lines.append(("heading", heading))
        for paragraph in paragraphs:
            lines.append(("body", paragraph))
    write_lines(doc, lines)
    doc.set_metadata(
        {
            "title": "Synthetic Middle Market Credit Memo",
            "author": "Tag Studio",
            "subject": "Synthetic credit memo fixture for local tagging tests",
            "keywords": "synthetic, credit memo, tagging, CRAIG, Tag Studio",
        }
    )
    doc.save(output_path)
    doc.close()


if __name__ == "__main__":
    build_pdf(OUTPUT_PATH)
    print(OUTPUT_PATH.resolve())
